### ISSUE TITLE
Error with linting

### ISSUE THREAD

**Issue by armano2** [mysticatea/vue-eslint-editor#3]
http://localhost:8080/vue-eslint-editor/

"Parsing error: acorn.Parser.extend is not a function"

```json
[{"ruleId":null,"fatal":true,"severity":2,"message":"Parsing error: acorn.Parser.extend is not a function","line":undefined,"column":undefined}]
```

there is something wrong, but i'm not able to pinpoint where, error is coming from linter -> eslint -> acorn,

 i didn't change code at all, just fresh pull/npm i/run docs

**Comment by mysticatea** [comment]
Sounds like you have encountered this npm's bug https://github.com/eslint/eslint/issues/11018.
Please try to remove package-lock.json and node_modules then re-install all.

**Comment by armano2** [comment]
ok :>
